"""create initial tables

Revision ID: 5c12f15d1693
Revises: 
Create Date: 2026-09-27 11:40:28.085031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c12f15d1693'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_slug')
    )
    op.create_table('product_color',
    sa.Column('color_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('color_code', sa.String(length=20), nullable=False),
    sa.Column('color_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('color_id')
    )
    op.create_table('product_size',
    sa.Column('size_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('size_name', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('size_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('post_code', sa.String(length=8), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_table('product_categories',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('product_id', 'category_id')
    )
    op.create_table('product_images',
    sa.Column('image_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('color_id', sa.BigInteger(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['product_color.color_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('product_variants',
    sa.Column('variant_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('color_id', sa.BigInteger(), nullable=False),
    sa.Column('size_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['product_color.color_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['product_size.size_id'], ),
    sa.PrimaryKeyConstraint('variant_id'),
    sa.UniqueConstraint('product_id', 'color_id', 'size_id', name='uq_product_variant')
    )
    op.create_table('user_address',
    sa.Column('address_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('last_name_kanji', sa.String(length=50), nullable=False),
    sa.Column('first_name_kanji', sa.String(length=50), nullable=False),
    sa.Column('last_name_katakana', sa.String(length=50), nullable=False),
    sa.Column('first_name_katakana', sa.String(length=50), nullable=False),
    sa.Column('post_number', sa.String(length=8), nullable=False),
    sa.Column('prefecture', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('street_address', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('cart_items',
    sa.Column('cart_item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.variant_id'], ),
    sa.PrimaryKeyConstraint('cart_item_id'),
    sa.UniqueConstraint('user_id', 'variant_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('address_id', sa.BigInteger(), nullable=False),
    sa.Column('subtotal_amount', sa.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('tax_amount', sa.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('ordered_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['user_address.address_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('order_items',
    sa.Column('order_item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=0), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.variant_id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    op.drop_table('cart_items')
    op.drop_table('user_address')
    op.drop_table('product_variants')
    op.drop_table('product_images')
    op.drop_table('product_categories')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('product_size')
    op.drop_table('product_color')
    op.drop_table('categories')
    # ### end Alembic commands ###
